-- Reset seguro (sem TRUNCATE)
SET @OLD_FK=@@FOREIGN_KEY_CHECKS; 
SET FOREIGN_KEY_CHECKS=0;

DELETE FROM pedido_item;
DELETE FROM pedido;
DELETE FROM reserva;
DELETE FROM cardapioitem;
DELETE FROM mesa;
DELETE FROM cliente;

-- resetar AUTO_INCREMENT
ALTER TABLE cliente      AUTO_INCREMENT = 1;
ALTER TABLE mesa         AUTO_INCREMENT = 1;
ALTER TABLE cardapioitem AUTO_INCREMENT = 1;
ALTER TABLE reserva      AUTO_INCREMENT = 1;
ALTER TABLE pedido       AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS=@OLD_FK;
